---

engine_version: "17.06"
docker_engine_debug: false
docker_ee_url: ""
engine_branch: "{{ (docker_ee_url != '' ) | ternary('stable', 'main') }}"
extra_daemon_options:
  "debug": "{{docker_engine_debug | bool }}"
