---

- hosts: all
  become: true
  roles:
    - ntp
    - docker-engine

- hosts: ucp-primary
  become: true
  roles:
    - docker-ucp-primary

- hosts: ucp-replica
  become: true
  serial: 1 # need to join one by one only
  roles:
    - docker-ucp-replica

- hosts: ucp-worker
  become: true
  roles:
    - docker-ucp-worker
