---

- name: "Test if UCP primary controller already exists"
  uri:
    url: "https://localhost/_ping"
    validate_certs: no
  register: ucp_primary
  ignore_errors: yes

- include: ucp-primary.yml
  when: ucp_primary.status != 200

