---

- set_fact:
    storage_driver: "aufs"

- name: "Install Docker apt key"
  apt_key:
    keyserver: "hkp://pool.sks-keyservers.net"
    id: "ee6d536cf7dc86e2d7d56f59a178ac6c6238f52e"
    state: present

- name: "Install Docker apt repo"
  apt_repository: 
    # select the repo based on distro and release codename: ubuntu-trusty, # debian-jessie, etc.
    repo: "deb https://packages.docker.com/{{ engine_version }}/apt/repo {{ ansible_distribution | lower }}-{{ansible_distribution_release}} {{ engine_branch }}"
    update_cache: yes
    state: present

- name: "Install Docker package"
  apt:
    name: docker-engine
    update_cache: yes
    state: installed
