---

#- include: ucp-iptables.yml

- name: test if ucp is already running on this node
  command: docker run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:{{ ucp_version }} id
  register: ucp_running
  ignore_errors: yes

- include: ucp-replica.yml
  when: "ucp_running.rc != 0"
